const ProgrammingLogType = {
	DELETED: 1,
	EDITED: 2,
	PYRAMID_ADDED: 3,
	REFRESHED: 4,
	ADDED: 5,
	PYRAMID_REMOVED: 6,
	BROKEN: 7,
	RTC_UPDATE: 8,
	STACK_UPDATE: 9,
	REPROGRAMMING: 10,
	SIM_CARD_DATA_DELETED: 11,
}
export {
	ProgrammingLogType
}