export const serviceReports = [
    {
		id: 14,
		name: 'События поручений по прибору учета',
		download: false,
		description: 'Количество событий по серийному номеру прибора учета',
	    executeFunction: 'dataInputReportDialogOpen',
		loading: false,
		show: false,
		open: true,
	},
	{
		id: 15,
		name: 'События поручений по адресу',
		download: false,
		description: 'Количество событий по адресу прибора учета',
		executeFunction: 'dataInputReportDialogOpen',
		loading: false,
		show: false,
		open: true,
	},
	{
		id: 18,
		name: 'Информация по поручениям за период',
		download: false,
		description: 'Информация по поручениям сгруппированная по статусу за период',
		executeFunction: 'dataInputReportDialogOpen',
		loading: false,
		show: false,
		open: false,
		print: true,
	},
	{
		id: 19,
		name: 'Информация по поручениям за период по сотруднику',
		download: false,
		description: 'Информация по поручениям сгруппированная по статусу и сотруднику за период',
		executeFunction: 'dataInputReportDialogOpen',
		loading: false,
		show: false,
		open: false,
		print: true,
	},
	{
		id: 20,
		name: 'Причины закрытия поручений',
		download: false,
		description: 'Информация по поручениям сгруппированная по причинам закрытия за весь период',
		executeFunction: 'showAssignmentEventsGroupByCloseReasonReport',
		loading: false,
		show: false,
		open: true,
	},
]
